version: '3'

volumes:
  database:
    external: false
  
  redis:
    external: false

services:
  database:
    image: postgres:11.6
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
    - "8080:8080"

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: dev_start
    entrypoint: /home/appuser/docker-entrypoint.sh
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./marketplace:/home/appuser/marketplace
      - ./config:/home/appuser/config
    ports:
      - "8000:8000"
    links:
      - database:database
      - redis:redis
