# Generated by Django 2.2.10 on 2020-02-11 00:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('appointment_reason', models.TextField(max_length=260)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_insurance', models.CharField(max_length=100)),
                ('patient_gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other'), ('PREFER NOT TO SAY', 'prefer not to say')], max_length=10)),
                ('patient_date_of_birth', models.DateField()),
                ('patient_phone_number', models.CharField(max_length=16)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Provider')),
            ],
        ),
    ]
