# Generated by Django 2.2.10 on 2020-02-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other'), ('PREFER NOT TO SAY', 'prefer not to say')], max_length=32),
        ),
    ]
